version: '3'
services:
  nginx:
    build:
      context: ./build/nginx
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./sample-web-app:/app:cached
    ports:
      - '80:80'
  redis:
    image: 'redis:latest'
  rabbitmq:
    image: 'rabbitmq:3.8-rc-management'
    environment:
      RABBITMQ_DEFAULT_USER: acme
      RABBITMQ_DEFAULT_PASS: acme
    ports:
      - '15672:15672'
      - "5672:5672"
    restart: always
    volumes:
      - ./build/rabbitmq:/var/lib/rabbitmq/mnesia
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./mysql/db:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
  php:
    build:
      context: ./build/php
      dockerfile: Dockerfile.dev
    volumes:
      - ./sample-web-app:/app:cached
    ports:
      - '9000:9000'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - '8080:80'
    links:
      - mysql
    environment:
      - PMA_HOST=mysql